name: docker release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set release env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: docker login
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          echo ${{ secrets.NEGASUS_PAT }} | docker login ghcr.io -u negasus --password-stdin

      - name: build and push
        run: |
          make build TAG=${{ env.RELEASE_VERSION }}
          make push TAG=${{ env.RELEASE_VERSION }}
